(ns movertone.scripts.samples)

(def bauli-files
  ["bauLi-BV-Raman,BV-Lakshmanan-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Chinmaya-Sisters---Uma,Radhika-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Gayathri-Venkataraghavan-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-KL-Sriram-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-KS-Rukmani-Venkatachalam-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Multiple-Artists-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Nanditha-Ravi-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Palghat-KV-Narayanaswamy-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-R-Ganesh-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Saranya-Krishnan-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Seetha-Rajan-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Sethalapathi-Balasubramaniam-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Subashree-Mani-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Subha-Ganesan-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Suguna-Purushothaman-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Trichur-V-Ramachandran-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Visalakshi-Nithyanand-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"
   "bauLi-Vyasarpadi-G-Kothandaraman-karuNAnidhiyE_tAyE-pApanAsam_sivan.mpeg.wav.pitch.frequencies"])

(def mohanam-files
  ["15mOhanam-Neyveli-Santhanagopalan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "17mOhanam-Maharajapuram-S-Srinivasan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "28mOhanam-Nagai-R-Muralidharan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "28mOhanam-U-Shrinivas-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "34mOhanam-ML-Vasanthakumari-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "35mOhanam-Padma-Chandilyan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "39mOhanam-U-Shrinivas-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "40mOhanam-Nedunuri-Krishnamurthy-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "54mOhanam-Sikkil-Mala-Chandrasekhar-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "55mOhanam-Seetha-Narayanan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "57mOhanam-ML-Vasanthakumari-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "59mOhanam-Parur-R-Venkataraman-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "60mOhanam-U-Shrinivas-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "70mOhanam-Sangeetha-Sivakumar-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "82mOhanam-Lalgudi-Vijayalakshmi-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "82mOhanam-Sudha-Raghunathan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "84mOhanam-Maharajapuram-S-Srinivasan-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "86mOhanam-VR-Dileepkumar-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "87mOhanam-Tadepalli-Lokanatha-Sharma-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"
   "96mOhanam-RS-Jayalakshmi-dayarAni_dayarAni_dAsharathi-tyAgarAja.mpeg.wav.pitch.frequencies"])

(def tracks ["valaji-varnam-bombay-jayashree.mp3.wav.pitch.frequencies"
             "04-sogasu_jUDa_taramA-kannaDagauLa.mp3.wav.pitch.frequencies"])

(def pancharatna-kritis
  ["Jagadanandakaraka.mp3.wav.pitch.frequencies"
   "Dudukugala.mp3.wav.pitch.frequencies"
   "Sadhinchane.mp3.wav.pitch.frequencies"
   "KanaKanaRuchira.mp3.wav.pitch.frequencies"
   "Endaro.mp3.wav.pitch.frequencies"])

(def generated
  ["foo.wav.wav.pitch.frequencies"
   "single-swaram-prob.wav.wav.pitch.frequencies"
   "two-swaram-prob.wav.wav.pitch.frequencies"
   "three-57564.wav.wav.pitch.frequencies"])

(def revati-files
  ["rEvati-Aruna-Sairam-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer11.mpeg.wav.pitch.frequencies"
   "rEvati-Aruna-Sairam-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer38.mpeg.wav.pitch.frequencies"
   "rEvati-Chinmaya-Sisters---Uma,Radhika-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer5.mpeg.wav.pitch.frequencies"
   "rEvati-Chinmaya-Sisters---Uma,Radhika-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer90.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer17.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer24.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer46.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer53.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer65.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer72.mpeg.wav.pitch.frequencies"
   "rEvati-DK-Jayaraman-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer96.mpeg.wav.pitch.frequencies"
   "rEvati-JB-Sruthisagar-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer69.mpeg.wav.pitch.frequencies"
   "rEvati-N-Ramani-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer59.mpeg.wav.pitch.frequencies"
   "rEvati-Niranjana-Srinivasan-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer85.mpeg.wav.pitch.frequencies"
   "rEvati-R-AthulKumar-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer63.mpeg.wav.pitch.frequencies"
   "rEvati-Sankaran-Namboodiri-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer91.mpeg.wav.pitch.frequencies"
   "rEvati-Sikkil-Sisters-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer1.mpeg.wav.pitch.frequencies"
   "rEvati-Subha-Ganesan-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer87.mpeg.wav.pitch.frequencies"
   "rEvati-Trichur-V-Ramachandran-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer36.mpeg.wav.pitch.frequencies"
   "rEvati-Trichur-V-Ramachandran-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer9.mpeg.wav.pitch.frequencies"
   "rEvati-V-Shankaranarayanan-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer45.mpeg.wav.pitch.frequencies"
   "rEvati-V-Shankaranarayanan-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer95.mpeg.wav.pitch.frequencies"
   "rEvati-VR-Dileepkumar-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer17.mpeg.wav.pitch.frequencies"
   "rEvati-Yogam-Santhanam-mahAdEva_shiva_shambhO-tanjAvUr_sankara_iyer65.mpeg.wav.pitch.frequencies"])

(def kalyani-files
  ["kalyANi-----nidhi_cAla_sukhamA-tyAgarAja87.mpeg.wav.pitch.frequencies"
   "kalyANi-Kunnakudi-R-Vaidyanathan-nidhi_cAla_sukhamA-tyAgarAja49.mpeg.wav.pitch.frequencies"
   "kalyANi-M-BalamuraliKrishna-nidhi_cAla_sukhamA-tyAgarAja22.mpeg.wav.pitch.frequencies"
   "kalyANi-MA-Sundareswaran-nidhi_cAla_sukhamA-tyAgarAja86.mpeg.wav.pitch.frequencies"
   "kalyANi-M-BalamuraliKrishna-nidhi_cAla_sukhamA-tyAgarAja60.mpeg.wav.pitch.frequencies"
   "kalyANi-Geetha-Raja-nidhi_cAla_sukhamA-tyAgarAja87.mpeg.wav.pitch.frequencies"
   "kalyANi-G-Ravi-Kiran-nidhi_cAla_sukhamA-tyAgarAja17.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Subbulakshmi-nidhi_cAla_sukhamA-tyAgarAja3.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Gopalakrishnan-nidhi_cAla_sukhamA-tyAgarAja69.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Anantharaman-nidhi_cAla_sukhamA-tyAgarAja76.mpeg.wav.pitch.frequencies"
   "kalyANi-Amritha-Murali-nidhi_cAla_sukhamA-tyAgarAja9.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Gopalakrishnan-nidhi_cAla_sukhamA-tyAgarAja84.mpeg.wav.pitch.frequencies"
   "kalyANi-M-BalamuraliKrishna-nidhi_cAla_sukhamA-tyAgarAja71.mpeg.wav.pitch.frequencies"
   "kalyANi-Palghat-R-Ramprasad-nidhi_cAla_sukhamA-tyAgarAja8.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Subbulakshmi-nidhi_cAla_sukhamA-tyAgarAja34.mpeg.wav.pitch.frequencies"
   "kalyANi-Maharajapuram-S-Srinivasan-nidhi_cAla_sukhamA-tyAgarAja70.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Gopalakrishnan-nidhi_cAla_sukhamA-tyAgarAja50.mpeg.wav.pitch.frequencies"
   "kalyANi-Palghat-R-Ramprasad-nidhi_cAla_sukhamA-tyAgarAja3.mpeg.wav.pitch.frequencies"
   "kalyANi-Maharajapuram-Santhanam-nidhi_cAla_sukhamA-tyAgarAja89.mpeg.wav.pitch.frequencies"
   "kalyANi-R-Parthasarathy-nidhi_cAla_sukhamA-tyAgarAja65.mpeg.wav.pitch.frequencies"
   "kalyANi-MS-Subbulakshmi-nidhi_cAla_sukhamA-tyAgarAja6.mpeg.wav.pitch.frequencies"
   "kalyANi-Ramnad-N-Krishnan-nidhi_cAla_sukhamA-tyAgarAja28.mpeg.wav.pitch.frequencies"
   "kalyANi-Ramnad-N-Krishnan-nidhi_cAla_sukhamA-tyAgarAja35.mpeg.wav.pitch.frequencies"
   "kalyANi-Palladam-S-Venkataramana-Rao-nidhi_cAla_sukhamA-tyAgarAja79.mpeg.wav.pitch.frequencies"
   "kalyANi-Raji-Gopalakrishnan-nidhi_cAla_sukhamA-tyAgarAja36.mpeg.wav.pitch.frequencies"
   "kalyANi-Raji-Gopalakrishnan-nidhi_cAla_sukhamA-tyAgarAja59.mpeg.wav.pitch.frequencies"
   "kalyANi-Ramnad-N-Krishnan-nidhi_cAla_sukhamA-tyAgarAja46.mpeg.wav.pitch.frequencies"
   "kalyANi-S-Seetharaman-nidhi_cAla_sukhamA-tyAgarAja42.mpeg.wav.pitch.frequencies"
   "kalyANi-TN-Krishnan,Viji-Krishnan-nidhi_cAla_sukhamA-tyAgarAja64.mpeg.wav.pitch.frequencies"
   "kalyANi-S-Sowmya-nidhi_cAla_sukhamA-tyAgarAja77.mpeg.wav.pitch.frequencies"
   "kalyANi-Ranjani,Gayathri-nidhi_cAla_sukhamA-tyAgarAja8.mpeg.wav.pitch.frequencies"
   "kalyANi-SP-Ramh-nidhi_cAla_sukhamA-tyAgarAja20.mpeg.wav.pitch.frequencies"
   "kalyANi-TN-Krishnan,Viji-Krishnan-nidhi_cAla_sukhamA-tyAgarAja69.mpeg.wav.pitch.frequencies"
   "kalyANi-Salem-Gayathri-Venkatesan-nidhi_cAla_sukhamA-tyAgarAja24.mpeg.wav.pitch.frequencies"
   "kalyANi-Tanjore-S-Kalyanaraman-nidhi_cAla_sukhamA-tyAgarAja81.mpeg.wav.pitch.frequencies"
   "kalyANi-TR-Subramaniam-nidhi_cAla_sukhamA-tyAgarAja44.mpeg.wav.pitch.frequencies"
   "kalyANi-VK-Raman-nidhi_cAla_sukhamA-tyAgarAja68.mpeg.wav.pitch.frequencies"])

(def my-records
  ["me-mohbeg-mach.wav.wav.pitch.frequencies"
   "me-mohbeg-me.wav.wav.pitch.frequencies"
   "me-mohmid-mach.wav.wav.pitch.frequencies"
   "me-mohmid-me.wav.wav.pitch.frequencies"])

(def gamakam-records
  ["gamakam-janti.wav-0.0000-4.4103.m4a.wav.pitch.frequencies"
   "gamakam-kampitam.wav-0.0000-5.3101.m4a.wav.pitch.frequencies"
   "gamakam-mpn-jaru-me.wav-0.0000-7.5566.m4a.wav.pitch.frequencies"
   "gamakam-orikai.wav-0.0000-6.9776.m4a.wav.pitch.frequencies"])

(def sah-records
  ["sah-var-mach.wav-0.0000-6.2592.m4a.wav.pitch.frequencies"
   "sah-var-machine-another-phrase.wav-0.0000-20.6251.m4a.wav.pitch.frequencies"
   "sah-var-me.wav-0.0000-6.6104.m4a.wav.pitch.frequencies"])

(def markov-generated
  ["gen-26776-raga-:kalyani-nth-order-2-gathi-30.wav.wav.pitch.frequencies"
   "gen-26812-raga-kalyani-nth-order-2-gathi-30.wav.wav.pitch.frequencies"
   "gen-26812-raga-kalyani-nth-order-2-gathi-30.wav.wav.wav.pitch.frequencies"
   "gen-26823-raga-kalyani-nth-order-3-gathi-30.wav.wav.pitch.frequencies"
   "gen-26823-raga-kalyani-nth-order-3-gathi-30.wav.wav.wav.pitch.frequencies"
   "gen-26834-raga-kalyani-nth-order-3-gathi-40.wav.wav.pitch.frequencies"
   "gen-26834-raga-kalyani-nth-order-3-gathi-40.wav.wav.wav.pitch.frequencies"
   "gen-26845-raga-kalyani-nth-order-4-gathi-40.wav.wav.pitch.frequencies"
   "gen-26845-raga-kalyani-nth-order-4-gathi-40.wav.wav.wav.pitch.frequencies"
   "gen-26856-raga-kalyani-nth-order-4-gathi-40.wav.wav.pitch.frequencies"
   "gen-26856-raga-kalyani-nth-order-4-gathi-40.wav.wav.wav.pitch.frequencies"
   "gen-26867-raga-kalyani-nth-order-4-gathi-40.wav.wav.pitch.frequencies"
   "gen-26867-raga-kalyani-nth-order-4-gathi-40.wav.wav.wav.pitch.frequencies"
   "gen-26878-raga-kalyani-nth-order-5-gathi-40.wav.wav.pitch.frequencies"
   "gen-26878-raga-kalyani-nth-order-5-gathi-40.wav.wav.wav.pitch.frequencies"
   "gen-26891-raga-kalyani-nth-order-5-gathi-40.wav.wav.pitch.frequencies"
   "gen-26891-raga-kalyani-nth-order-5-gathi-40.wav.wav.wav.pitch.frequencies"
   "gen-26927-raga-kalyani-nth-order-5-gathi-50.wav.wav.pitch.frequencies"
   "gen-26938-raga-kalyani-nth-order-5-gathi-50.wav.wav.pitch.frequencies"
   "gen-26949-raga-kalyani-nth-order-5-gathi-40.wav.wav.pitch.frequencies"
   "gen-26960-raga-kalyani-nth-order-6-gathi-40.wav.wav.pitch.frequencies"
   "gen-26971-raga-kalyani-nth-order-6-gathi-40.wav.wav.pitch.frequencies"
   "gen-26982-raga-kalyani-nth-order-6-gathi-50.wav.wav.pitch.frequencies"
   "gen-26993-raga-kalyani-nth-order-6-gathi-50.wav.wav.pitch.frequencies"
   "gen-27006-raga-kalyani-nth-order-7-gathi-50.wav.wav.pitch.frequencies"
   "gen-27017-raga-kalyani-nth-order-7-gathi-50.wav.wav.pitch.frequencies"
   "gen-27028-raga-kalyani-nth-order-7-gathi-40.wav.wav.pitch.frequencies"
   "gen-27039-raga-kalyani-nth-order-7-gathi-40.wav.wav.pitch.frequencies"
   "gen-27050-raga-kalyani-nth-order-7-gathi-40.wav.wav.pitch.frequencies"
   "gen-27061-raga-kalyani-nth-order-8-gathi-40.wav.wav.pitch.frequencies"
   "gen-27074-raga-kalyani-nth-order-8-gathi-40.wav.wav.pitch.frequencies"
   "gen-27085-raga-kalyani-nth-order-8-gathi-40.wav.wav.pitch.frequencies"
   "gen-27096-raga-kalyani-nth-order-8-gathi-40.wav.wav.pitch.frequencies"
   "gen-27107-raga-kalyani-nth-order-8-gathi-50.wav.wav.pitch.frequencies"
   "gen-27118-raga-kalyani-nth-order-8-gathi-60.wav.wav.pitch.frequencies"
   "gen-27129-raga-kalyani-nth-order-8-gathi-40.wav.wav.pitch.frequencies"
   "gen-27140-raga-kalyani-nth-order-9-gathi-40.wav.wav.pitch.frequencies"
   "gen-27153-raga-kalyani-nth-order-9-gathi-40.wav.wav.pitch.frequencies"
   "gen-27379-raga-kalyani-nth-order-9-gathi-40.wav.wav.pitch.frequencies"
   "gen-27390-raga-kalyani-nth-order-9-gathi-50.wav.wav.pitch.frequencies"
   "gen-27503-raga-kalyani-nth-order-9-gathi-50.wav.wav.pitch.frequencies"
   "gen-27514-raga-kalyani-nth-order-9-gathi-40.wav.wav.pitch.frequencies"
   "gen-27525-raga-kalyani-nth-order-9-gathi-40.wav.wav.pitch.frequencies"
   "gen-27548-raga-kalyani-nth-order-10-gathi-40.wav.wav.pitch.frequencies"
   "gen-27559-raga-kalyani-nth-order-10-gathi-40.wav.wav.pitch.frequencies"
   "gen-27570-raga-kalyani-nth-order-10-gathi-100.wav.wav.pitch.frequencies"
   "gen-27581-raga-kalyani-nth-order-10-gathi-100.wav.wav.pitch.frequencies"
   "gen-27595-raga-kalyani-nth-order-10-gathi-70.wav.wav.pitch.frequencies"
   "gen-27607-raga-kalyani-nth-order-10-gathi-50.wav.wav.pitch.frequencies"
   "gen-27643-raga-kalyani-nth-order-10-gathi-50.wav.wav.pitch.frequencies"
   "gen-27654-raga-kalyani-nth-order-10-gathi-100.wav.wav.pitch.frequencies"])
